# Generated by Django 3.2.15 on 2022-09-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220909_1823'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='follow_user_author_constraint',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='follow_user_author_constraint'),
        ),
    ]
